server:
  port: 8080

spring:
  datasource:
    jdbc-url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:

  secondary-datasource:
    jdbc-url: ${SECONDARY_DB_URL}
    username: ${SECONDARY_DB_USERNAME}
    password: ${SECONDARY_DB_PASSWORD}
    driver-class-name: org.postgresql.Driver


    jpa:
      hibernate:
        ddl-auto: update
      show-sql: true
      properties:
        hibernate:
          format_sql: true
          dialect: org.hibernate.dialect.H2Dialect
      open-in-view: false

    thymeleaf:
      cache: false

    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}

secondary:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    org.hibernate.SQL: debug